import {Injectable} from '@angular/core';

@Injectable()
export class Globals {
    public readonly FHIRUrls = {
        ImplementationGuide: 'http://hl7.org/fhir/StructureDefinition/ImplementationGuide',
        StructureDefinition: 'http://hl7.org/fhir/StructureDefinition/StructureDefinition'
    };

    public readonly ResourceTypes = {
        'Account': { code: 'Account', display: 'Account' },
        'ActivityDefinition': { code: 'ActivityDefinition', display: 'ActivityDefinition' },
        'AdverseEvent': { code: 'AdverseEvent', display: 'AdverseEvent' },
        'AllergyIntolerance': { code: 'AllergyIntolerance', display: 'AllergyIntolerance' },
        'Appointment': { code: 'Appointment', display: 'Appointment' },
        'AppointmentResponse': { code: 'AppointmentResponse', display: 'AppointmentResponse' },
        'AuditEvent': { code: 'AuditEvent', display: 'AuditEvent' },
        'Basic': { code: 'Basic', display: 'Basic' },
        'Binary': { code: 'Binary', display: 'Binary' },
        'BodySite': { code: 'BodySite', display: 'BodySite' },
        'Bundle': { code: 'Bundle', display: 'Bundle' },
        'CapabilityStatement': { code: 'CapabilityStatement', display: 'CapabilityStatement' },
        'CarePlan': { code: 'CarePlan', display: 'CarePlan' },
        'CareTeam': { code: 'CareTeam', display: 'CareTeam' },
        'ChargeItem': { code: 'ChargeItem', display: 'ChargeItem' },
        'Claim': { code: 'Claim', display: 'Claim' },
        'ClaimResponse': { code: 'ClaimResponse', display: 'ClaimResponse' },
        'ClinicalImpression': { code: 'ClinicalImpression', display: 'ClinicalImpression' },
        'CodeSystem': { code: 'CodeSystem', display: 'CodeSystem' },
        'Communication': { code: 'Communication', display: 'Communication' },
        'CommunicationRequest': { code: 'CommunicationRequest', display: 'CommunicationRequest' },
        'CompartmentDefinition': { code: 'CompartmentDefinition', display: 'CompartmentDefinition' },
        'Composition': { code: 'Composition', display: 'Composition' },
        'ConceptMap': { code: 'ConceptMap', display: 'ConceptMap' },
        'Condition': { code: 'Condition', display: 'Condition' },
        'Consent': { code: 'Consent', display: 'Consent' },
        'Contract': { code: 'Contract', display: 'Contract' },
        'Coverage': { code: 'Coverage', display: 'Coverage' },
        'DataElement': { code: 'DataElement', display: 'DataElement' },
        'DetectedIssue': { code: 'DetectedIssue', display: 'DetectedIssue' },
        'Device': { code: 'Device', display: 'Device' },
        'DeviceComponent': { code: 'DeviceComponent', display: 'DeviceComponent' },
        'DeviceMetric': { code: 'DeviceMetric', display: 'DeviceMetric' },
        'DeviceRequest': { code: 'DeviceRequest', display: 'DeviceRequest' },
        'DeviceUseStatement': { code: 'DeviceUseStatement', display: 'DeviceUseStatement' },
        'DiagnosticReport': { code: 'DiagnosticReport', display: 'DiagnosticReport' },
        'DocumentManifest': { code: 'DocumentManifest', display: 'DocumentManifest' },
        'DocumentReference': { code: 'DocumentReference', display: 'DocumentReference' },
        'DomainResource': { code: 'DomainResource', display: 'DomainResource' },
        'EligibilityRequest': { code: 'EligibilityRequest', display: 'EligibilityRequest' },
        'EligibilityResponse': { code: 'EligibilityResponse', display: 'EligibilityResponse' },
        'Encounter': { code: 'Encounter', display: 'Encounter' },
        'Endpoint': { code: 'Endpoint', display: 'Endpoint' },
        'EnrollmentRequest': { code: 'EnrollmentRequest', display: 'EnrollmentRequest' },
        'EnrollmentResponse': { code: 'EnrollmentResponse', display: 'EnrollmentResponse' },
        'EpisodeOfCare': { code: 'EpisodeOfCare', display: 'EpisodeOfCare' },
        'ExpansionProfile': { code: 'ExpansionProfile', display: 'ExpansionProfile' },
        'ExplanationOfBenefit': { code: 'ExplanationOfBenefit', display: 'ExplanationOfBenefit' },
        'FamilyMemberHistory': { code: 'FamilyMemberHistory', display: 'FamilyMemberHistory' },
        'Flag': { code: 'Flag', display: 'Flag' },
        'Goal': { code: 'Goal', display: 'Goal' },
        'GraphDefinition': { code: 'GraphDefinition', display: 'GraphDefinition' },
        'Group': { code: 'Group', display: 'Group' },
        'GuidanceResponse': { code: 'GuidanceResponse', display: 'GuidanceResponse' },
        'HealthcareService': { code: 'HealthcareService', display: 'HealthcareService' },
        'ImagingManifest': { code: 'ImagingManifest', display: 'ImagingManifest' },
        'ImagingStudy': { code: 'ImagingStudy', display: 'ImagingStudy' },
        'Immunization': { code: 'Immunization', display: 'Immunization' },
        'ImmunizationRecommendation': { code: 'ImmunizationRecommendation', display: 'ImmunizationRecommendation' },
        'ImplementationGuide': { code: 'ImplementationGuide', display: 'ImplementationGuide' },
        'Library': { code: 'Library', display: 'Library' },
        'Linkage': { code: 'Linkage', display: 'Linkage' },
        'List': { code: 'List', display: 'List' },
        'Location': { code: 'Location', display: 'Location' },
        'Measure': { code: 'Measure', display: 'Measure' },
        'MeasureReport': { code: 'MeasureReport', display: 'MeasureReport' },
        'Media': { code: 'Media', display: 'Media' },
        'Medication': { code: 'Medication', display: 'Medication' },
        'MedicationAdministration': { code: 'MedicationAdministration', display: 'MedicationAdministration' },
        'MedicationDispense': { code: 'MedicationDispense', display: 'MedicationDispense' },
        'MedicationRequest': { code: 'MedicationRequest', display: 'MedicationRequest' },
        'MedicationStatement': { code: 'MedicationStatement', display: 'MedicationStatement' },
        'MessageDefinition': { code: 'MessageDefinition', display: 'MessageDefinition' },
        'MessageHeader': { code: 'MessageHeader', display: 'MessageHeader' },
        'NamingSystem': { code: 'NamingSystem', display: 'NamingSystem' },
        'NutritionOrder': { code: 'NutritionOrder', display: 'NutritionOrder' },
        'Observation': { code: 'Observation', display: 'Observation' },
        'OperationDefinition': { code: 'OperationDefinition', display: 'OperationDefinition' },
        'OperationOutcome': { code: 'OperationOutcome', display: 'OperationOutcome' },
        'Organization': { code: 'Organization', display: 'Organization' },
        'Parameters': { code: 'Parameters', display: 'Parameters' },
        'Patient': { code: 'Patient', display: 'Patient' },
        'PaymentNotice': { code: 'PaymentNotice', display: 'PaymentNotice' },
        'PaymentReconciliation': { code: 'PaymentReconciliation', display: 'PaymentReconciliation' },
        'Person': { code: 'Person', display: 'Person' },
        'PlanDefinition': { code: 'PlanDefinition', display: 'PlanDefinition' },
        'Practitioner': { code: 'Practitioner', display: 'Practitioner' },
        'PractitionerRole': { code: 'PractitionerRole', display: 'PractitionerRole' },
        'Procedure': { code: 'Procedure', display: 'Procedure' },
        'ProcedureRequest': { code: 'ProcedureRequest', display: 'ProcedureRequest' },
        'ProcessRequest': { code: 'ProcessRequest', display: 'ProcessRequest' },
        'ProcessResponse': { code: 'ProcessResponse', display: 'ProcessResponse' },
        'Provenance': { code: 'Provenance', display: 'Provenance' },
        'Questionnaire': { code: 'Questionnaire', display: 'Questionnaire' },
        'QuestionnaireResponse': { code: 'QuestionnaireResponse', display: 'QuestionnaireResponse' },
        'ReferralRequest': { code: 'ReferralRequest', display: 'ReferralRequest' },
        'RelatedPerson': { code: 'RelatedPerson', display: 'RelatedPerson' },
        'RequestGroup': { code: 'RequestGroup', display: 'RequestGroup' },
        'ResearchStudy': { code: 'ResearchStudy', display: 'ResearchStudy' },
        'ResearchSubject': { code: 'ResearchSubject', display: 'ResearchSubject' },
        'Resource': { code: 'Resource', display: 'Resource' },
        'RiskAssessment': { code: 'RiskAssessment', display: 'RiskAssessment' },
        'Schedule': { code: 'Schedule', display: 'Schedule' },
        'SearchParameter': { code: 'SearchParameter', display: 'SearchParameter' },
        'Sequence': { code: 'Sequence', display: 'Sequence' },
        'ServiceDefinition': { code: 'ServiceDefinition', display: 'ServiceDefinition' },
        'Slot': { code: 'Slot', display: 'Slot' },
        'Specimen': { code: 'Specimen', display: 'Specimen' },
        'StructureDefinition': { code: 'StructureDefinition', display: 'StructureDefinition' },
        'StructureMap': { code: 'StructureMap', display: 'StructureMap' },
        'Subscription': { code: 'Subscription', display: 'Subscription' },
        'Substance': { code: 'Substance', display: 'Substance' },
        'SupplyDelivery': { code: 'SupplyDelivery', display: 'SupplyDelivery' },
        'SupplyRequest': { code: 'SupplyRequest', display: 'SupplyRequest' },
        'Task': { code: 'Task', display: 'Task' },
        'TestReport': { code: 'TestReport', display: 'TestReport' },
        'TestScript': { code: 'TestScript', display: 'TestScript' },
        'ValueSet': { code: 'ValueSet', display: 'ValueSet' },
        'VisionPrescription': { code: 'VisionPrescription', display: 'VisionPrescription' }
    };

    public fhirDefinedTypes = [
        'Address',
        'Age',
        'Annotation',
        'Attachment',
        'BackboneElement',
        'CodeableConcept',
        'Coding',
        'ContactDetail',
        'ContactPoint',
        'Contributor',
        'Count',
        'DataRequirement',
        'Distance',
        'Dosage',
        'Duration',
        'Element',
        'ElementDefinition',
        'Extension',
        'HumanName',
        'Identifier',
        'MarketingStatus',
        'Meta',
        'Money',
        'Narrative',
        'ParameterDefinition',
        'Period',
        'ProdCharacteristic',
        'ProductShelfLife',
        'Quantity',
        'Range',
        'Ratio',
        'Reference',
        'RelatedArtifact',
        'SampledData',
        'Signature',
        'SimpleQuantity',
        'SubstanceAmount',
        'SubstanceMoiety',
        'Timing',
        'TriggerDefinition',
        'UsageContext',
        'base64Binary',
        'boolean',
        'canonical',
        'code',
        'date',
        'dateTime',
        'decimal',
        'id',
        'instant',
        'integer',
        'markdown',
        'oid',
        'positiveInt',
        'string',
        'time',
        'unsignedInt',
        'uri',
        'url',
        'uuid',
        'xhtml',
        'Account',
        'ActivityDefinition',
        'AdverseEvent',
        'AllergyIntolerance',
        'Appointment',
        'AppointmentResponse',
        'AuditEvent',
        'Basic',
        'Binary',
        'BiologicallyDerivedProduct',
        'BodyStructure',
        'Bundle',
        'CapabilityStatement',
        'CarePlan',
        'CareTeam',
        'ChargeItem',
        'Claim',
        'ClaimResponse',
        'ClinicalImpression',
        'CodeSystem',
        'Communication',
        'CommunicationRequest',
        'CompartmentDefinition',
        'Composition',
        'ConceptMap',
        'Condition',
        'Consent',
        'Contract',
        'Coverage',
        'DetectedIssue',
        'Device',
        'DeviceComponent',
        'DeviceMetric',
        'DeviceRequest',
        'DeviceUseStatement',
        'DiagnosticReport',
        'DocumentManifest',
        'DocumentReference',
        'DomainResource',
        'EligibilityRequest',
        'EligibilityResponse',
        'Encounter',
        'Endpoint',
        'EnrollmentRequest',
        'EnrollmentResponse',
        'EntryDefinition',
        'EpisodeOfCare',
        'EventDefinition',
        'ExampleScenario',
        'ExpansionProfile',
        'ExplanationOfBenefit',
        'FamilyMemberHistory',
        'Flag',
        'Goal',
        'GraphDefinition',
        'Group',
        'GuidanceResponse',
        'HealthcareService',
        'ImagingStudy',
        'Immunization',
        'ImmunizationEvaluation',
        'ImmunizationRecommendation',
        'ImplementationGuide',
        'Invoice',
        'ItemInstance',
        'Library',
        'Linkage',
        'List',
        'Location',
        'Measure',
        'MeasureReport',
        'Media',
        'Medication',
        'MedicationAdministration',
        'MedicationDispense',
        'MedicationKnowledge',
        'MedicationRequest',
        'MedicationStatement',
        'MedicinalProduct',
        'MedicinalProductAuthorization',
        'MedicinalProductClinicals',
        'MedicinalProductDeviceSpec',
        'MedicinalProductIngredient',
        'MedicinalProductPackaged',
        'MedicinalProductPharmaceutical',
        'MessageDefinition',
        'MessageHeader',
        'NamingSystem',
        'NutritionOrder',
        'Observation',
        'ObservationDefinition',
        'OccupationalData',
        'OperationDefinition',
        'OperationOutcome',
        'Organization',
        'OrganizationRole',
        'Parameters',
        'Patient',
        'PaymentNotice',
        'PaymentReconciliation',
        'Person',
        'PlanDefinition',
        'Practitioner',
        'PractitionerRole',
        'Procedure',
        'ProcessRequest',
        'ProcessResponse',
        'ProductPlan',
        'Provenance',
        'Questionnaire',
        'QuestionnaireResponse',
        'RelatedPerson',
        'RequestGroup',
        'ResearchStudy',
        'ResearchSubject',
        'Resource',
        'RiskAssessment',
        'Schedule',
        'SearchParameter',
        'Sequence',
        'ServiceRequest',
        'Slot',
        'Specimen',
        'SpecimenDefinition',
        'StructureDefinition',
        'StructureMap',
        'Subscription',
        'Substance',
        'SubstancePolymer',
        'SubstanceReferenceInformation',
        'SubstanceSpecification',
        'SupplyDelivery',
        'SupplyRequest',
        'Task',
        'TerminologyCapabilities',
        'TestReport',
        'TestScript',
        'UserSession',
        'ValueSet',
        'VerificationResult',
        'VisionPrescription'
    ];

    public tooltips = {
        'resource.id': 'The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.',
        'sd.name': 'A natural language name identifying the structure definition. This name should be usable as an identifier for the module by machine processing applications such as code generation.',
        'sd.url': 'An absolute URI that is used to identify this structure definition when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which this structure definition is (or will be) published.',
        'sd.title': 'A short, descriptive, user-friendly title for the structure definition.',
        'sd.date': 'The date (and optionally time) when the structure definition was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the structure definition changes.',
        'sd.publisher': 'The name of the organization or individual that published the structure definition.',
        'sd.description': 'A free text natural language description of the structure definition from a consumer\'s perspective.',
        'sd.version': 'The identifier that is used to identify this version of the structure definition when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the structure definition author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence.',
        'sd.status': 'The status of this structure definition. Enables tracking the life-cycle of the content.',
        'sd.experimental': 'A Boolean value to indicate that this structure definition is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage.',
        'ed.representation': 'Codes that define how this element is ' +
            'represented in instances, when the deviation varies from the normal case.',
        'ed.code': 'A code that has the same meaning as the element in a particular terminology.',
        'ed.min': 'The minimum number of times this element SHALL appear in the instance.',
        'ed.max': 'The maximum number of times this element is permitted to appear in the instance.',
        'ed.type': 'The data type or resource that the value of this element is permitted to be.',
        'ed.type.code': 'URL of Data type or Resource that is a(or the) type used for this element. References are URLs that are relative to http://hl7.org/fhir/StructureDefinition e.g. "string" is a reference to http://hl7.org/fhir/StructureDefinition/string. Absolute URLs are only allowed in logical models.',
        'ed.type.profile': 'Identifies a profile structure or implementation Guide that applies to the datatype this element refers to. If any profiles are specified, then the content must conform to at least one of them. The URL can be a local reference - to a contained StructureDefinition, or a reference to another StructureDefinition or Implementation Guide by a canonical URL. When an implementation guide is specified, the type SHALL conform to at least one profile defined in the implementation guide.',
        'ed.type.targetProfile': 'Used when the type is "Reference", and Identifies a profile structure or implementation Guide that applies to the target of the reference this element refers to. If any profiles are specified, then the content must conform to at least one of them. The URL can be a local reference - to a contained StructureDefinition, or a reference to another StructureDefinition or Implementation Guide by a canonical URL. When an implementation guide is specified, the target resource SHALL conform to at least one profile defined in the implementation guide.',
        'ed.type.aggregation': 'If the type is a reference to another resource, how the resource is or can be aggregated - is it a contained resource, or a reference, and if the context is a bundle, is it included in the bundle.',
        'ed.type.versioning': 'Whether this reference needs to be version specific or version independent, or whether either can be used.'
    };

    public generateRandomNumber(min: number, max: number): number {
        return Math.floor(Math.random() * (max - min + 1)) + min;
    }

    public toggleProperty(parent, propertyName, defaultValue) {
        if (parent.hasOwnProperty(propertyName)) {
            delete parent[propertyName];
        } else {
            parent[propertyName] = defaultValue;
        }
    }

    public getShortString(theString: string, pre: boolean = true, length: number = 20): string {
        if (theString && theString.length > length) {
            if (pre) {
                return theString.substring(0, length) + '...';
            } else {
                return '...' + theString.substring(theString.length - length);
            }
        }

        return theString;
    }

    public promptForRemove(array: any[], index: number, message = 'Are you sure you want to remove this item?') {
        if (confirm(message)) {
            array.splice(index, 1);
        }
    }
}
